### ISSUE TITLE
How to choice between fastapi-observability and opentelemetry-apm

### ISSUE THREAD

**Issue by npuichigo** [Blueswen/fastapi-observability#13]
I would like to ask the difference between this repo and https://github.com/blueswen/opentelemetry-apm/tree/main, since they all use Tempo and Prometheus, and the difference is whether to use opentelemetry collector. Which service infrastructure is better or how to choose which one to use? Any advice? Thanks

**Comment by blueswen** [comment]
Based on your requirements. This repo demonstrates how to collect metrics, logs, and traces generated by the application itself. [OpenTelemetry Application Performance Management](https://github.com/blueswen/opentelemetry-apm/tree/main) assumes application unable to provide metrics by itself, so we have to generate metrics from traces information leverage [Span Metrics Connector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/spanmetricsconnector/README.md) from OpenTelemetry collector.

Since you understand Chinese, I have written a series of posts talking about Observability and a tutorial on how to build an observability platform from ground. That may help you understand how to choose a tech stack that fits your requirements.
1. [時光之鏡：透視過去、現在與未來的 Observability](https://ithelp.ithome.com.tw/users/20162175/ironman/6445)
2. [從零開始打造可觀測性平台](https://speakerdeck.com/blueswen/cong-ling-kai-shi-da-zao-ke-guan-ce-xing-ping-tai)

**Comment by npuichigo** [comment]
Great tutorial and materials, thanks a lot!
